### PR TITLE
Fix linter

### PR DESCRIPTION
**Pull request by jaas666**
My attempt at fixing the linter #7 . Also fixed the errors that were present.

I'm no expert so please review/test before merging.

I tested on my side by creating an error on one of the files and it was caught when I tried to commit the file so I think it's working.

image

### CODE REVIEW

**Comment by Divide-By-0** [comment]
Awesome! Rebase main then we can merge?

**Comment by jaas666** [comment]
Should be ready to go

**Comment by Divide-By-0** [comment]
@jaas666 There seems to be a problem with your update to Image on `yarn build`/`next build`. I've reverted till it can be fixed!

```
Nov 12 10:17:05 PM  Error occurred prerendering page "/app". Read more: https://nextjs.org/docs/messages/prerender-error
Nov 12 10:17:05 PM  Error: Image with src "/copy.png" is missing "loader" prop.
Nov 12 10:17:05 PM  Read more: https://nextjs.org/docs/messages/next-image-missing-loader
Nov 12 10:17:05 PM      at getImgProps (/opt/render/project/src/node_modules/next/dist/shared/lib/get-img-props.js:149:19)
Nov 12 10:17:05 PM      at /opt/render/project/src/.next/server/chunks/92.js:31667:82
Nov 12 10:17:05 PM      at Ue (/opt/render/project/src/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:117:330)
Nov 12 10:17:05 PM      at Z (/opt/render/project/src/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)
Nov 12 10:17:05 PM      at Ve (/opt/render/project/src/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:123:155)
Nov 12 10:17:05 PM      at Ue (/opt/render/project/src/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:114:215)
Nov 12 10:17:05 PM      at Z (/opt/render/project/src/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)
Nov 12 10:17:05 PM      at Ve (/opt/render/project/src/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:123:155)
Nov 12 10:17:05 PM      at Xe (/opt/render/project/src/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:122:289)
Nov 12 10:17:05 PM      at Z (/opt/render/project/src/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:350)
Nov 12 10:17:05 PM  - info Generating static pages (4/9)
Nov 12 10:17:05 PM  - info Generating static pages (6/9)
Nov 12 10:17:05 PM  - info Generating static pages (9/9)
Nov 12 10:17:05 PM  
Nov 12 10:17:05 PM  > Export encountered errors on following paths:
Nov 12 10:17:05 PM      /(main)/(routes)/app/page: /app
Nov 12 10:17:11 PM  error Command failed with exit code 1.
Nov 12 10:17:11 PM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jaas666** [comment]
Hmm. Can you switch them back to regular img tags?

I'll take a look when I'm back home.

Will probably get warnings but should allow the commit

**Pull request merged**
