### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by wryonik**
image
image
image

### CODE REVIEW

**Comment by Divide-By-0** [comment]
I don't like that we moved the max into the currency drop-down. Can we fix that

**Comment by wryonik** [comment]
Do you want it below the currency dropdown as it is in the current version, or is there something else on your mind?

**Comment by Divide-By-0** [comment]
> Do you want it below the currency dropdown as it is in the current version, or is there something else on your mind?

What do other websites do?

**Comment by wryonik** [comment]
Metamask shows just below the amount input field
image

Uniswap also follows same design
image
 
Coindcx shows in a different place. If we want to follow above designs, I can add the max value below the amounts input field?

**Comment by Divide-By-0** [comment]
Yes, below seems better.

**Comment by wryonik** [comment]
Updated. This is how it looks in the newer version
image
image

**Comment by Divide-By-0** [comment]
Screenshot_20240818_113743_Chrome
Mobile view looks weird and squished

**Comment by wryonik** [comment]
How does this feel?
image
image
The dropdown has a lighter shade in light mode. Do you want me to increase its contract a bit or does this seems fine?
image

**Comment by Divide-By-0** [comment]
UI Audit
- contrast on NFTs is bad i.e. the disabled tab in the send section
- the dark mode hover tooltip of the tokens
- it says 'email is invalid character at position 65' at the bottom fo the deposit page
- make the hyperlinks use an accent color
- hyperlink the user's address in deposit page to etherscan

later
- make the ux of the text instructions under 'send assets via email' look more elegant via cards
- change brown on email wallet to the yellow to unify the sites, color palettes, and brands

**Pull request merged**
